/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaoDienApp;

import gmailApi.Init;
import gmailApi.MessageObject;
import java.util.List;
import java.awt.Panel;
import java.io.File;
import java.util.ArrayList;
import javafx.application.Application;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import customException.FailToLoadInitInboxException;
import gmailApi.GlobalVariable;
import gmailApi.MessageProcess;
import gmailApi.XuLyFile;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author NTA
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public index() {
	setLocation(450, 200);
	initComponents();
	loadStartUpMailBox();
	list_mailbox_panel.setVisible(true);
	read_mail_panel.setVisible(false);
	write_mail_panel.setVisible(false);

    }
    List<MessageObject> messageInbox;
//    ArrayList<MessageObject> demo = new ArrayList<>();    
//    MessageObject demo1 = new MessageObject("Tuan@gmail.com", "Deadline", "2 tuan truoc thi !", "20/03/2020", "tuan");                                       //đổ dữ liệu để test thôi
//    MessageObject demo2 = new MessageObject("Thom@gmail.com", "Hello ", "How are you to day", "10/04/2020", "thom");                                         //
//    MessageObject demo3 = new MessageObject("An@gmail.com", "Demo", " aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaâ", "15/04/2020", "An");   //
//    MessageObject demo4 = new MessageObject("Tuan1@gmail.com", "Deadline1", "2 tuan truoc thi !", "20/03/2020", "tuan");                                       //đổ dữ liệu để test thôi
//    MessageObject demo5 = new MessageObject("Thom1@gmail.com", "Hello1 ", "How are you to day", "10/04/2020", "thom");                                         //
//    MessageObject demo6 = new MessageObject("An1@gmail.com", "Demo1", " aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaâ", "15/04/2020", "An");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        write_mail_panel = new javax.swing.JPanel();
        lb_nothing1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        write_mail_to = new javax.swing.JTextField();
        write_mail_cc = new javax.swing.JTextField();
        write_mail_bcc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        write_mail_sub = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        write_mail_content = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        write_mail_sent = new javax.swing.JLabel();
        write_mail_cancel = new javax.swing.JLabel();
        lb_ = new javax.swing.JLabel();
        write_mail_select_file = new javax.swing.JButton();
        write_mail_file_name = new javax.swing.JTextField();
        write_mail_from = new javax.swing.JTextField();
        read_mail_file_cbx = new javax.swing.JTextField();
        background_all = new javax.swing.JPanel();
        read_mail_panel = new javax.swing.JPanel();
        lb_nothing2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        read_mail_content = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        read_mail_to = new javax.swing.JTextField();
        read_mail_cc = new javax.swing.JTextField();
        read_mail_bcc = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        read_mail_sub = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        read_mail_reply = new javax.swing.JLabel();
        read_mail_trash = new javax.swing.JLabel();
        lb_1 = new javax.swing.JLabel();
        read_mail_download = new javax.swing.JLabel();
        read_mail_file_Jcb = new javax.swing.JComboBox<>();
        read_mail_from = new javax.swing.JTextField();
        read_mail_date = new javax.swing.JTextField();
        adddd = new javax.swing.JLabel();
        menu_panel = new javax.swing.JPanel();
        lb_hide_menu = new javax.swing.JLabel();
        menu_new_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu_trash_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menu_mailbox_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menu_mailbox_panel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        list_mailbox_panel = new javax.swing.JPanel();
        list_mailbox_search = new javax.swing.JTextField();
        mailbox_search = new javax.swing.JLabel();
        mailbox_reset = new javax.swing.JLabel();
        jScroll_mailbox = new javax.swing.JScrollPane();
        list_mailbox = new javax.swing.JList<>();
        lb_name = new javax.swing.JLabel();
        prevLoadMail_Bt = new javax.swing.JButton();
        nextLoadMail_Bt = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        lb_name_mail = new javax.swing.JLabel();
        background_img = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        write_mail_panel.setOpaque(false);

        lb_nothing1.setText("From :");

        jLabel4.setText("To :");

        jLabel15.setText("Cc :");

        jLabel16.setText("Bcc :");

        write_mail_to.setOpaque(false);
        write_mail_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                write_mail_toActionPerformed(evt);
            }
        });

        write_mail_cc.setOpaque(false);

        write_mail_bcc.setOpaque(false);

        jLabel17.setText("Subject :");

        write_mail_sub.setOpaque(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        write_mail_content.setColumns(20);
        write_mail_content.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        write_mail_content.setLineWrap(true);
        write_mail_content.setRows(5);
        jScrollPane1.setViewportView(write_mail_content);

        jPanel2.setBackground(new java.awt.Color(39, 129, 191));

        write_mail_sent.setBackground(new java.awt.Color(39, 129, 191));
        write_mail_sent.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        write_mail_sent.setForeground(new java.awt.Color(255, 255, 255));
        write_mail_sent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sent-35.png"))); // NOI18N
        write_mail_sent.setText("Sent");
        write_mail_sent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        write_mail_sent.setOpaque(true);
        write_mail_sent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                write_mail_sentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                write_mail_sentMouseExited(evt);
            }
        });

        write_mail_cancel.setBackground(new java.awt.Color(39, 129, 191));
        write_mail_cancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        write_mail_cancel.setForeground(new java.awt.Color(255, 255, 255));
        write_mail_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancel-35.png"))); // NOI18N
        write_mail_cancel.setText("Cancel");
        write_mail_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        write_mail_cancel.setOpaque(true);
        write_mail_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                write_mail_cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                write_mail_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                write_mail_cancelMouseExited(evt);
            }
        });

        lb_.setBackground(new java.awt.Color(39, 129, 191));
        lb_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lb_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-file-30.png"))); // NOI18N
        lb_.setText("File ");

        write_mail_select_file.setBackground(new java.awt.Color(39, 129, 191));
        write_mail_select_file.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        write_mail_select_file.setText("Select file");
        write_mail_select_file.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        write_mail_select_file.setOpaque(false);
        write_mail_select_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                write_mail_select_fileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lb_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(write_mail_file_name, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(write_mail_select_file)
                .addGap(18, 18, 18)
                .addComponent(write_mail_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(write_mail_sent, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(write_mail_sent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(write_mail_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lb_, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(write_mail_select_file, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(write_mail_file_name, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        write_mail_from.setEditable(false);

        javax.swing.GroupLayout write_mail_panelLayout = new javax.swing.GroupLayout(write_mail_panel);
        write_mail_panel.setLayout(write_mail_panelLayout);
        write_mail_panelLayout.setHorizontalGroup(
            write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, write_mail_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, write_mail_panelLayout.createSequentialGroup()
                        .addGroup(write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nothing1)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(write_mail_to)
                            .addComponent(write_mail_from)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, write_mail_panelLayout.createSequentialGroup()
                        .addGroup(write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(write_mail_bcc)
                            .addComponent(write_mail_cc)
                            .addComponent(write_mail_sub)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        write_mail_panelLayout.setVerticalGroup(
            write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(write_mail_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nothing1)
                    .addComponent(write_mail_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(write_mail_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(write_mail_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(write_mail_bcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(write_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(write_mail_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        write_mail_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel15, jLabel16, jLabel4, lb_nothing1});

        write_mail_panel.getAccessibleContext().setAccessibleName("");

        read_mail_file_cbx.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 625));

        background_all.setFocusable(false);
        background_all.setMinimumSize(new java.awt.Dimension(1000, 625));
        background_all.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        read_mail_panel.setOpaque(false);

        lb_nothing2.setText("From :");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setOpaque(false);

        read_mail_content.setEditable(false);
        read_mail_content.setColumns(20);
        read_mail_content.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        read_mail_content.setLineWrap(true);
        read_mail_content.setRows(5);
        jScrollPane4.setViewportView(read_mail_content);

        jLabel10.setText("To :");

        jLabel18.setText("Cc :");

        jLabel19.setText("Bcc :");

        read_mail_to.setEditable(false);
        read_mail_to.setOpaque(false);
        read_mail_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_mail_toActionPerformed(evt);
            }
        });

        read_mail_cc.setEditable(false);
        read_mail_cc.setOpaque(false);

        read_mail_bcc.setEditable(false);
        read_mail_bcc.setOpaque(false);

        jLabel20.setText("Subject :");

        read_mail_sub.setEditable(false);
        read_mail_sub.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(39, 129, 191));

        read_mail_reply.setBackground(new java.awt.Color(39, 129, 191));
        read_mail_reply.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        read_mail_reply.setForeground(new java.awt.Color(255, 255, 255));
        read_mail_reply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-reply-arrow-35.png"))); // NOI18N
        read_mail_reply.setText("Reply");
        read_mail_reply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        read_mail_reply.setOpaque(true);
        read_mail_reply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                read_mail_replyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                read_mail_replyMouseExited(evt);
            }
        });

        read_mail_trash.setBackground(new java.awt.Color(39, 129, 191));
        read_mail_trash.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        read_mail_trash.setForeground(new java.awt.Color(255, 255, 255));
        read_mail_trash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancel-35.png"))); // NOI18N
        read_mail_trash.setText("Trash");
        read_mail_trash.setToolTipText("Move current mail to trash");
        read_mail_trash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        read_mail_trash.setOpaque(true);
        read_mail_trash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                read_mail_trashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                read_mail_trashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                read_mail_trashMouseExited(evt);
            }
        });

        lb_1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lb_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-file-30.png"))); // NOI18N
        lb_1.setText("File ");

        read_mail_download.setBackground(new java.awt.Color(39, 129, 191));
        read_mail_download.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        read_mail_download.setForeground(new java.awt.Color(255, 255, 255));
        read_mail_download.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-download-35.png"))); // NOI18N
        read_mail_download.setText("Save mail");
        read_mail_download.setToolTipText("Download current mail");
        read_mail_download.setAlignmentX(0.2F);
        read_mail_download.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        read_mail_download.setOpaque(true);
        read_mail_download.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                read_mail_downloadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                read_mail_downloadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                read_mail_downloadMouseExited(evt);
            }
        });

        read_mail_file_Jcb.setToolTipText("Click on file to download");
        read_mail_file_Jcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_mail_file_JcbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lb_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(read_mail_file_Jcb, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(read_mail_download)
                .addGap(24, 24, 24)
                .addComponent(read_mail_trash, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(read_mail_reply, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_1)
                    .addComponent(read_mail_file_Jcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read_mail_download, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(read_mail_trash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(read_mail_reply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        read_mail_from.setEditable(false);
        read_mail_from.setOpaque(false);
        read_mail_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_mail_fromActionPerformed(evt);
            }
        });

        read_mail_date.setEditable(false);
        read_mail_date.setOpaque(false);
        read_mail_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_mail_dateActionPerformed(evt);
            }
        });

        adddd.setText("Date :");

        javax.swing.GroupLayout read_mail_panelLayout = new javax.swing.GroupLayout(read_mail_panel);
        read_mail_panel.setLayout(read_mail_panelLayout);
        read_mail_panelLayout.setHorizontalGroup(
            read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(read_mail_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(read_mail_panelLayout.createSequentialGroup()
                        .addGroup(read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel10)
                            .addComponent(lb_nothing2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(read_mail_to)
                            .addComponent(read_mail_bcc)
                            .addComponent(read_mail_cc)
                            .addComponent(read_mail_sub)
                            .addGroup(read_mail_panelLayout.createSequentialGroup()
                                .addComponent(read_mail_from)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(adddd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read_mail_date, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        read_mail_panelLayout.setVerticalGroup(
            read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(read_mail_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adddd)
                        .addComponent(read_mail_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_nothing2)
                        .addComponent(read_mail_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read_mail_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(read_mail_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(read_mail_bcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(read_mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read_mail_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        background_all.add(read_mail_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 80, 690, 552));

        menu_panel.setBackground(new java.awt.Color(54, 70, 78));
        menu_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_hide_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-menu-30.png"))); // NOI18N
        lb_hide_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_hide_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hide_menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_hide_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_hide_menuMouseExited(evt);
            }
        });
        menu_panel.add(lb_hide_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 40));

        menu_new_panel.setToolTipText("New");
        menu_new_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_new_panel.setOpaque(false);
        menu_new_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_new_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_new_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_new_panelMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-file-40.png"))); // NOI18N

        javax.swing.GroupLayout menu_new_panelLayout = new javax.swing.GroupLayout(menu_new_panel);
        menu_new_panel.setLayout(menu_new_panelLayout);
        menu_new_panelLayout.setHorizontalGroup(
            menu_new_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_new_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        menu_new_panelLayout.setVerticalGroup(
            menu_new_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_new_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_panel.add(menu_new_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 65, 60));

        menu_trash_panel.setToolTipText("Trash");
        menu_trash_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_trash_panel.setOpaque(false);
        menu_trash_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_trash_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_trash_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_trash_panelMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-trash-45.png"))); // NOI18N

        javax.swing.GroupLayout menu_trash_panelLayout = new javax.swing.GroupLayout(menu_trash_panel);
        menu_trash_panel.setLayout(menu_trash_panelLayout);
        menu_trash_panelLayout.setHorizontalGroup(
            menu_trash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_trash_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_trash_panelLayout.setVerticalGroup(
            menu_trash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_trash_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_panel.add(menu_trash_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 65, 60));

        menu_mailbox_panel.setToolTipText("Mail Box");
        menu_mailbox_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_mailbox_panel.setOpaque(false);
        menu_mailbox_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_mailbox_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_mailbox_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_mailbox_panelMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-chat-message-sent-45.png"))); // NOI18N

        javax.swing.GroupLayout menu_mailbox_panelLayout = new javax.swing.GroupLayout(menu_mailbox_panel);
        menu_mailbox_panel.setLayout(menu_mailbox_panelLayout);
        menu_mailbox_panelLayout.setHorizontalGroup(
            menu_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_mailbox_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_mailbox_panelLayout.setVerticalGroup(
            menu_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_mailbox_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_panel.add(menu_mailbox_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 65, 60));

        menu_mailbox_panel1.setToolTipText("Mail Box");
        menu_mailbox_panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_mailbox_panel1.setOpaque(false);
        menu_mailbox_panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_mailbox_panel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_mailbox_panel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_mailbox_panel1MouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-upload-mail-40.png"))); // NOI18N

        javax.swing.GroupLayout menu_mailbox_panel1Layout = new javax.swing.GroupLayout(menu_mailbox_panel1);
        menu_mailbox_panel1.setLayout(menu_mailbox_panel1Layout);
        menu_mailbox_panel1Layout.setHorizontalGroup(
            menu_mailbox_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_mailbox_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        menu_mailbox_panel1Layout.setVerticalGroup(
            menu_mailbox_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_mailbox_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_panel.add(menu_mailbox_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 65, 60));

        background_all.add(menu_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 65, 560));

        list_mailbox_panel.setBackground(new java.awt.Color(255, 255, 255));

        list_mailbox_search.setOpaque(false);

        mailbox_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-20.png"))); // NOI18N

        mailbox_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-reset-28.png"))); // NOI18N

        list_mailbox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        list_mailbox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        list_mailbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_mailboxMouseClicked(evt);
            }
        });
        list_mailbox.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_mailboxValueChanged(evt);
            }
        });
        jScroll_mailbox.setViewportView(list_mailbox);

        lb_name.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lb_name.setText("Mail Box");

        prevLoadMail_Bt.setText("<");

        nextLoadMail_Bt.setText(">");

        javax.swing.GroupLayout list_mailbox_panelLayout = new javax.swing.GroupLayout(list_mailbox_panel);
        list_mailbox_panel.setLayout(list_mailbox_panelLayout);
        list_mailbox_panelLayout.setHorizontalGroup(
            list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScroll_mailbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(list_mailbox_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(list_mailbox_panelLayout.createSequentialGroup()
                        .addComponent(list_mailbox_search, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mailbox_search, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mailbox_reset)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(list_mailbox_panelLayout.createSequentialGroup()
                        .addComponent(prevLoadMail_Bt)
                        .addGap(34, 34, 34)
                        .addComponent(lb_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextLoadMail_Bt)
                        .addGap(24, 24, 24))))
        );
        list_mailbox_panelLayout.setVerticalGroup(
            list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_mailbox_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list_mailbox_search, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(mailbox_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mailbox_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScroll_mailbox, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevLoadMail_Bt)
                    .addComponent(lb_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextLoadMail_Bt))
                .addContainerGap())
        );

        background_all.add(list_mailbox_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 75, 250, 550));

        logo.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        logo.setForeground(new java.awt.Color(172, 93, 93));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.setText("GMAIL");
        background_all.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        lb_name_mail.setForeground(new java.awt.Color(255, 255, 255));
        lb_name_mail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-change-user-45.png"))); // NOI18N
        background_all.add(lb_name_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 210, 30));

        background_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FMainMenu.png"))); // NOI18N
        background_img.setText("jLabel1");
        background_all.add(background_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_all, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_all, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_trash_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_trash_panelMouseExited
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_trash_panelMouseExited

    private void menu_trash_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_trash_panelMouseEntered
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_trash_panelMouseEntered

    private void menu_new_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_new_panelMouseExited
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_new_panelMouseExited

    private void menu_new_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_new_panelMouseEntered
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_new_panelMouseEntered

    private void lb_hide_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hide_menuMouseExited

    }//GEN-LAST:event_lb_hide_menuMouseExited

    private void lb_hide_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hide_menuMouseEntered

    }//GEN-LAST:event_lb_hide_menuMouseEntered

    private void lb_hide_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hide_menuMouseClicked
	// TODO add your handling code here:
//        panelcoler(menu_mailbox_panel);
//        panelreset(menu_new_panel);
//        panelreset(menu_trash_panel);
//        if (x == 65) {
//            menu_panel.setSize(x, 552);
//            Thread th;
//            th = new Thread() {
//                @Override
//                public void run() {
//                    try {
//                        for (int i = 65; i <= x; i++) {
//                            Thread.sleep(1);
//                            menu_panel.setSize(i, 552);
//                        }
//                    } catch (InterruptedException e) {
//                        JOptionPane.showMessageDialog(null, e);
//                    }
//                }
//            };
//            th.start();
//            list_mailbox_panel.setVisible(false);
//            x = 315;
//        } else if (x == 315) {
//            menu_panel.setSize(315, 552);
//            Thread th;
//            th = new Thread() {
//                @Override
//                public void run() {
//                    try {
//
//                        for (int i = 315; i >= 65; i--) {
//                            Thread.sleep(1);
//                            menu_panel.setSize(i, 552);
//
//                            a++;
//                        }
//                    } catch (InterruptedException e) {
//                        JOptionPane.showMessageDialog(null, e);
//                    }
//                }
//            };
//            th.start();
//            list_mailbox_panel.setVisible(true);
//            x = 65;
//        }
    }//GEN-LAST:event_lb_hide_menuMouseClicked
    String name;
    private void menu_mailbox_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panelMouseExited
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_mailbox_panelMouseExited

    private void menu_mailbox_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panelMouseEntered
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_mailbox_panelMouseEntered

    private void menu_mailbox_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panelMouseClicked
	// TODO add your handling code here:
	name = "mail box";
	panelreset(menu_trash_panel);
	panelcoler(menu_mailbox_panel);
	panelreset(menu_new_panel);
	write_mail_panel.setVisible(false);
	list_mailbox_panel.setVisible(true);
	read_mail_panel.setVisible(true);
	loadStartUpMailBox();
    }//GEN-LAST:event_menu_mailbox_panelMouseClicked

    private void list_mailboxValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_mailboxValueChanged
	// TODO add your handling code here:
    }//GEN-LAST:event_list_mailboxValueChanged

    private void list_mailboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_mailboxMouseClicked
	// TODO add your handling code here:
	int chon = list_mailbox.getSelectedIndex();
	if (chon != -1) {
	    write_mail_panel.setVisible(false);
	    read_mail_panel.setVisible(true);
	    panelreset(menu_trash_panel);
	    panelcoler(menu_mailbox_panel);
	    panelreset(menu_new_panel);
	    MessageObject msgOb = messageInbox.get(chon);
	    MessageProcess.loadMessage(msgOb);
	    read_mail_from.setText(msgOb.from);
	    read_mail_to.setText(msgOb.to);
	    read_mail_cc.setText(msgOb.cc);
	    read_mail_sub.setText(msgOb.subject);
	    read_mail_date.setText(msgOb.date);
	    read_mail_content.setText(msgOb.mainText);
	    // load file len
	    DefaultComboBoxModel model = new DefaultComboBoxModel();
	    for (Map.Entry m : msgOb.listFile.entrySet()) {
		model.addElement(m.getKey());
	    }
	    this.read_mail_file_Jcb.setModel(model);
	    // vo hieu hoa bcc vi reader khong the thay bcc
	    read_mail_bcc.setEnabled(true);
	    read_mail_panel.setVisible(true);
	}
    }//GEN-LAST:event_list_mailboxMouseClicked

    private void menu_trash_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_trash_panelMouseClicked
	// TODO add your handling code here:
	name = "trash";
	panelcoler(menu_trash_panel);
	panelreset(menu_mailbox_panel);
	panelreset(menu_new_panel);
	showListTrashDemo();
    }//GEN-LAST:event_menu_trash_panelMouseClicked

    private void menu_new_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_new_panelMouseClicked
	// TODO add your handling code here:
	panelreset(menu_trash_panel);
	panelreset(menu_mailbox_panel);
	panelcoler(menu_new_panel);
	read_mail_panel.setVisible(false);
	write_mail_panel.setVisible(true);
    }//GEN-LAST:event_menu_new_panelMouseClicked

    private void write_mail_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_write_mail_toActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_write_mail_toActionPerformed

    private void write_mail_select_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_write_mail_select_fileActionPerformed
	// TODO add your handling code here:
	JFileChooser fileChooser = new JFileChooser();
	fileChooser.setDialogTitle("Select file");
	String linkFile;
	int userSelection = fileChooser.showOpenDialog(this);
	if (userSelection == JFileChooser.APPROVE_OPTION) {
	    File fileToOpen = fileChooser.getSelectedFile();
	    linkFile = fileToOpen.getAbsolutePath();
	    write_mail_file_name.setText(linkFile);
	}
    }//GEN-LAST:event_write_mail_select_fileActionPerformed

    private void write_mail_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_write_mail_cancelMouseClicked
	// TODO add your handling code here:
	int ans = JOptionPane.showConfirmDialog(this, "Do you want to save to draft ?");
	if (ans == JOptionPane.YES_OPTION) {
	    lb_.setText("File :");
	    write_mail_bcc.setText("");
	    write_mail_cc.setText("");
	    write_mail_sub.setText("");
	    write_mail_to.setText("");
	    write_mail_content.setText("");
	}
    }//GEN-LAST:event_write_mail_cancelMouseClicked

    private void write_mail_sentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_write_mail_sentMouseEntered
	// TODO add your handling code here:
	labelcolor(write_mail_sent);
    }//GEN-LAST:event_write_mail_sentMouseEntered

    private void write_mail_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_write_mail_cancelMouseEntered
	// TODO add your handling code here:
	labelcolor(write_mail_cancel);
    }//GEN-LAST:event_write_mail_cancelMouseEntered

    private void write_mail_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_write_mail_cancelMouseExited
	// TODO add your handling code here:
	resetlabelcolor(write_mail_cancel);
    }//GEN-LAST:event_write_mail_cancelMouseExited

    private void write_mail_sentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_write_mail_sentMouseExited
	// TODO add your handling code here:
	resetlabelcolor(write_mail_sent);
    }//GEN-LAST:event_write_mail_sentMouseExited

    private void read_mail_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_mail_toActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_read_mail_toActionPerformed

    private void read_mail_replyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_replyMouseEntered
	// TODO add your handling code here:
	labelcolor(read_mail_reply);
    }//GEN-LAST:event_read_mail_replyMouseEntered

    private void read_mail_replyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_replyMouseExited
	// TODO add your handling code here:
	resetlabelcolor(read_mail_reply);
    }//GEN-LAST:event_read_mail_replyMouseExited
    private void cleanReadMailPanel() {
	read_mail_from.setText("");
	read_mail_bcc.setText("");
	read_mail_cc.setText("");
	read_mail_sub.setText("");
	read_mail_to.setText("");
	read_mail_content.setText("");
	read_mail_file_Jcb.removeAllItems();
	read_mail_date.setText("");
	int index = list_mailbox.getSelectedIndex();
	DefaultListModel listMail = (DefaultListModel) list_mailbox.getModel();
	listMail.remove(index);
	list_mailbox.setModel(listMail);
	messageInbox.remove(index);
    }
    private void read_mail_trashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_trashMouseClicked
	// TODO add your handling code here:
	int confirmResponse = JOptionPane.showConfirmDialog(this, "Bạn có chăc muốn đưa mail này vào thùng rác không?");
	if (confirmResponse == JOptionPane.YES_OPTION) {
	    int chon = list_mailbox.getSelectedIndex();
	    MessageObject msgOb = messageInbox.get(chon);
	    try {
		MessageProcess.moveToTrash(msgOb.id);
		cleanReadMailPanel();
	    } catch (IOException ex) {
		Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
	    }
	}
    }//GEN-LAST:event_read_mail_trashMouseClicked

    private void read_mail_trashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_trashMouseEntered
	// TODO add your handling code here:
	labelcolor(read_mail_trash);
    }//GEN-LAST:event_read_mail_trashMouseEntered

    private void read_mail_trashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_trashMouseExited
	// TODO add your handling code here:
	resetlabelcolor(read_mail_trash);
    }//GEN-LAST:event_read_mail_trashMouseExited

    private void read_mail_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_mail_fromActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_read_mail_fromActionPerformed

    private void read_mail_downloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_downloadMouseClicked
	// TODO add your handling code here:
//	System.out.println("click on download !");
	String pathDir = XuLyFile.showOpenDirDialog();
	int chon = list_mailbox.getSelectedIndex();
	MessageObject msgOb = messageInbox.get(chon);
	MessageProcess.saveMail(msgOb, pathDir);
    }//GEN-LAST:event_read_mail_downloadMouseClicked

    private void read_mail_downloadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_downloadMouseEntered
	// TODO add your handling code here:
	labelcolor(read_mail_download);
    }//GEN-LAST:event_read_mail_downloadMouseEntered

    private void read_mail_downloadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_downloadMouseExited
	// TODO add your handling code here:
	resetlabelcolor(read_mail_download);
    }//GEN-LAST:event_read_mail_downloadMouseExited

    private void read_mail_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_mail_dateActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_read_mail_dateActionPerformed

    private void menu_mailbox_panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panel1MouseClicked
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_mailbox_panel1MouseClicked

    private void menu_mailbox_panel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panel1MouseEntered
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_mailbox_panel1MouseEntered

    private void menu_mailbox_panel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panel1MouseExited
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_mailbox_panel1MouseExited

    private void read_mail_file_JcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_mail_file_JcbActionPerformed
	try {
	    // TODO add your handling code here:
	    String pathDir = XuLyFile.showOpenDirDialog();
	    String fileName = (String) this.read_mail_file_Jcb.getSelectedItem();
	    String fileAttId;
	    int chon = list_mailbox.getSelectedIndex();
	    MessageObject msgOb = messageInbox.get(chon);
	    fileAttId = msgOb.listFile.get(fileName);
	    MessageProcess.downloadAttach(msgOb.id, fileAttId, pathDir + fileName);
	} catch (IOException ex) {
	    Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_read_mail_file_JcbActionPerformed

    /**
     * * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new index().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adddd;
    private javax.swing.JPanel background_all;
    private javax.swing.JLabel background_img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScroll_mailbox;
    private javax.swing.JLabel lb_;
    private javax.swing.JLabel lb_1;
    private javax.swing.JLabel lb_hide_menu;
    private javax.swing.JLabel lb_name;
    public static javax.swing.JLabel lb_name_mail;
    private javax.swing.JLabel lb_nothing1;
    private javax.swing.JLabel lb_nothing2;
    private javax.swing.JList<MessageObject> list_mailbox;
    private javax.swing.JPanel list_mailbox_panel;
    private javax.swing.JTextField list_mailbox_search;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mailbox_reset;
    private javax.swing.JLabel mailbox_search;
    private javax.swing.JPanel menu_mailbox_panel;
    private javax.swing.JPanel menu_mailbox_panel1;
    private javax.swing.JPanel menu_new_panel;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JPanel menu_trash_panel;
    private javax.swing.JButton nextLoadMail_Bt;
    private javax.swing.JButton prevLoadMail_Bt;
    private javax.swing.JTextField read_mail_bcc;
    private javax.swing.JTextField read_mail_cc;
    private javax.swing.JTextArea read_mail_content;
    private javax.swing.JTextField read_mail_date;
    private javax.swing.JLabel read_mail_download;
    private javax.swing.JComboBox<String> read_mail_file_Jcb;
    private javax.swing.JTextField read_mail_file_cbx;
    private javax.swing.JTextField read_mail_from;
    private javax.swing.JPanel read_mail_panel;
    private javax.swing.JLabel read_mail_reply;
    private javax.swing.JTextField read_mail_sub;
    public static javax.swing.JTextField read_mail_to;
    private javax.swing.JLabel read_mail_trash;
    private javax.swing.JTextField write_mail_bcc;
    private javax.swing.JLabel write_mail_cancel;
    private javax.swing.JTextField write_mail_cc;
    private javax.swing.JTextArea write_mail_content;
    private javax.swing.JTextField write_mail_file_name;
    public static javax.swing.JTextField write_mail_from;
    private javax.swing.JPanel write_mail_panel;
    private javax.swing.JButton write_mail_select_file;
    private javax.swing.JLabel write_mail_sent;
    private javax.swing.JTextField write_mail_sub;
    private javax.swing.JTextField write_mail_to;
    // End of variables declaration//GEN-END:variables
    private void labelcolor(JLabel label) {
	label.setBackground(new java.awt.Color(53, 162, 107));
    }

    private void resetlabelcolor(JLabel label) {
	label.setBackground(new java.awt.Color(39, 129, 191));
    }

    private void panelcoler(JPanel panel) {
	panel.setOpaque(true);
	panel.setBackground(new java.awt.Color(39, 129, 191));
    }

    private void panelreset(JPanel panel) {
	panel.setOpaque(false);
	panel.setBackground(new java.awt.Color(54, 70, 78));

    }

    private void loadStartUpMailBox() {
	if (GlobalVariable.internetOn = true) {
	    lb_name.setText("Mail Box");
	    DefaultListModel listMail = new DefaultListModel(); // khởi tạo Listmodel để đổ dữ liệu vào
	    try {
		messageInbox = Init.initStartUpInboxList();

		list_mailbox.setModel(listMail);                      // đổ dữ liệu từ listmodel đã tạo ở trên vào cái hiển thị
		list_mailbox.setCellRenderer(new mailListRender());   // set các cell trong list lại .
		for (int i = 0; i < messageInbox.size(); i++) {
		    listMail.add(i, messageInbox.get(i));
		}
	    } catch (FailToLoadInitInboxException ex) {
		Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
	    }
	} else {

	}
    }

    private void showListTrashDemo() {
//        lb_name.setText("Trash");
//        DefaultListModel listMail2 = new DefaultListModel(); // khởi tạo Listmodel để đổ dữ liệu vào
//        demo.add(3, demo4);
//        demo.add(4, demo5);
//        demo.add(5, demo6);
//        list_mailbox.setModel(listMail2);                      // đổ dữ liệu từ listmodel đã tạo ở trên vào cái hiển thị
//        list_mailbox.setCellRenderer(new mailListRender());   // set các cell trong list lại .
//        listMail2.add(0, demo.get(3));
//        listMail2.add(1, demo.get(4));
//        listMail2.add(2, demo.get(5));
    }
}
