/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaoDienApp;

import gmailApi.MessageObject;
import gmailApi.SendMailProcess;
import java.awt.Frame;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ReplyMailFrame extends javax.swing.JFrame {

    /**
     * Creates new form waitingFrame
     */
    MessageObject msgOb;

    // if click cancel; returnValue = false
    public ReplyMailFrame(newMainPage parent, MessageObject msgOb) {
	this.msgOb = msgOb;
	initComponents();
	userNameReply_Lb.setText(msgOb.from);
	replyText_Tarea.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameReply_Lb = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        replyText_Tarea = new javax.swing.JTextField();
        sentReply_Bt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cancel_Bt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 400));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(161, 233, 237));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(161, 233, 237));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Trả lời đến:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 30));

        userNameReply_Lb.setBackground(new java.awt.Color(161, 233, 237));
        userNameReply_Lb.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jPanel1.add(userNameReply_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 620, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 640, 10));

        replyText_Tarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replyText_TareaActionPerformed(evt);
            }
        });
        jPanel1.add(replyText_Tarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 640, 250));

        sentReply_Bt.setBackground(new java.awt.Color(161, 233, 237));
        sentReply_Bt.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        sentReply_Bt.setText("SENT");
        sentReply_Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentReply_BtActionPerformed(evt);
            }
        });
        jPanel1.add(sentReply_Bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 100, -1));

        jLabel3.setBackground(new java.awt.Color(161, 233, 237));
        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setText("Nội dung:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        cancel_Bt.setBackground(new java.awt.Color(161, 233, 237));
        cancel_Bt.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        cancel_Bt.setText("CANCEL");
        cancel_Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_BtActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_Bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void replyText_TareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replyText_TareaActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_replyText_TareaActionPerformed

    private void sentReply_BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentReply_BtActionPerformed
	// TODO add your handling code here:
	try {
	    String replyMessage = replyText_Tarea.getText();
	    SendMailProcess.reply(msgOb, replyMessage);
	    JOptionPane.showMessageDialog(this, "Bạn đã gửi thành công !");
	} catch (IOException ex) {
	    Logger.getLogger(newMainPage.class.getName()).log(Level.SEVERE, null, ex);
	}
	this.dispose();
    }//GEN-LAST:event_sentReply_BtActionPerformed

    private void cancel_BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_BtActionPerformed
	// TODO add your handling code here:
	this.dispose();
    }//GEN-LAST:event_cancel_BtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(ReplyMailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(ReplyMailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(ReplyMailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(ReplyMailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
//	java.awt.EventQueue.invokeLater(new Runnable() {
//	    public void run() {
//		new ReplyMailFrame().setVisible(true);
//	    }
//	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_Bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField replyText_Tarea;
    private javax.swing.JButton sentReply_Bt;
    private javax.swing.JLabel userNameReply_Lb;
    // End of variables declaration//GEN-END:variables
}
